name: triton
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.11.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1n
  - pillow=9.0.1
  - pip=21.2.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.13
  - python_abi=3.8
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.27.1
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.2
  - tbb=2021.3.0
  - tk=8.6.11
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - typing_extensions=4.1.1
  - urllib3=1.26.8
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
      - --find-links https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html
      - detectron2==0.6+cu113
      - opencv-python-headless

variables:
  PYTHONNOUSERSITE: 1
